version: '3.4'

services:
  db:
    image: pokeapi-heart-challenge-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: pokeapi-heart-challenge
    ports:
      - 3308:3306
    networks:
      - udemy-network

  pokeapi-heart-challenge-application:
    image: pokeapi-heart-challenge-backend
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - udemy-network
  
  pokeapi-heart-challenge-client:
    image: pokeapi-heart-challenge-frontend
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 80:80
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - db
    networks:
      - udemy-network

networks:
  udemy-network:
    driver: bridge
